# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frequency.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x66requency.proto\"\x91\x01\n\x13\x46requencyDictionary\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x36\n\tfrequency\x18\x02 \x03(\x0b\x32#.FrequencyDictionary.FrequencyEntry\x1a\x30\n\x0e\x46requencyEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'frequency_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FREQUENCYDICTIONARY_FREQUENCYENTRY._options = None
  _FREQUENCYDICTIONARY_FREQUENCYENTRY._serialized_options = b'8\001'
  _FREQUENCYDICTIONARY._serialized_start=20
  _FREQUENCYDICTIONARY._serialized_end=165
  _FREQUENCYDICTIONARY_FREQUENCYENTRY._serialized_start=117
  _FREQUENCYDICTIONARY_FREQUENCYENTRY._serialized_end=165
# @@protoc_insertion_point(module_scope)
